# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b8bc7213d729583dc2f629341525126cf883a79d8d2ccdaa8742f9296295b0b5f0d70fbad840bab55f909b5cf21066bef020cd3b6abe4f3028bc673676c0f4

test:
  secret_key_base: 534f5dfc8a1eaf036f90d38872e8967dccd42ae0a0c4d77a4ac69c3e0275542a0f857d9f156fc4ca20dbd9ba9083fe2774b9b38e12d382a8f1cdfa4601be5236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
